#!/bin/bash

#    ____ _
#   / ___| |__   ___  _ __ ___  ___
#  | |   | '_ \ / _ \| '__/ _ \/ __|
#  | |___| | | | (_) | | |  __/\__ \
#   \____|_| |_|\___/|_|  \___||___/
#
#- from github.com/basnijholt/home-assistant-config

python3 utils/commit-updates.py
pip3 -q install pyfiglet
python3 utils/ascii_art.py
python3 utils/update-readme.py
./utils/commit-readme.sh
