---
#-
#                  _             _                  _ _       _
#   ___ ___  _ __ | |_ _ __ ___ | |    _____      _(_) |_ ___| |__   ___  ___
#  / __/ _ \| '_ \| __| '__/ _ \| |   / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# | (_| (_) | | | | |_| | | (_) | |   \__ \\ V  V /| | || (__| | | |  __/\__ \
#  \___\___/|_| |_|\__|_|  \___/|_|___|___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#                                |_____|
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Control switches: living room Philips Hue dimmer switch"
  mode: parallel
  triggers:
    trigger: mqtt
    topic: "zigbee2mqtt/Dimmer Switch (Living room)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Next color
      - conditions: "{{ action == 'off_press' }}" # Lowest button
        sequence:
          action: script.next_colors
          data:
            input_select: input_select.last_script_living_room

      # Bright lights
      - conditions:
          - "{{ action == 'up_press' }}" # Second from highest button
          - condition: state
            entity_id: light.living_room_lights
            state: "on"
        sequence:
          - action: script.white_lights_living_room
          - action: light.turn_on
            entity_id: light.living_room_lights
            data:
              brightness: "255"

      # Increase brightness
      - conditions: "{{ action == 'on_press' }}" # Top button
        sequence:
          action: script.increase_brightness
          data:
            group: light.living_room_lights

      # Turn on
      - conditions:
          - "{{ action == 'up_press' }}" # Second from highest button
          - condition: state
            entity_id: light.living_room_lights
            state: "off"
        sequence:
          - action: light.turn_on
            entity_id: light.living_room_lights

      # Turn off
      - conditions:
          - "{{ action == 'down_press' }}" # Second from lowest button
          - condition: state
            entity_id: light.living_room_lights
            state: "on"
        sequence:
          - action: light.turn_off
            entity_id: light.living_room_lights

      # Reset adaptive_lighting
      - conditions:
          - "{{ action == 'up_hold' }}" # Second from highest button
          - "{{ trigger.payload_json.action_duration > 2 }}" # Hold for more than two seconds
        sequence:
          - action: script.reset_adaptive_lighting

- alias: "Control switches: bedroom Philips Hue dimmer switch"
  mode: parallel
  triggers:
    trigger: mqtt
    topic: "zigbee2mqtt/Dimmer Switch (Bedroom)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Next color
      - conditions: "{{ action == 'off_press' }}" # Lowest button
        sequence:
          action: script.next_colors
          data:
            input_select: input_select.last_script_bedroom

      # Bright lights
      - conditions:
          - "{{ action == 'up_press' }}" # Second from highest button
          - condition: state
            entity_id: light.bedroom_lights
            state: "on"
        sequence:
          - action: script.white_lights_bedroom
          - action: light.turn_on
            entity_id: light.bedroom_lights
            data:
              brightness: "255"

      # Increase brightness
      - conditions: "{{ action == 'on_press' }}" # Top button
        sequence:
          action: script.increase_brightness
          data:
            group: light.bedroom_lights

      # Turn on
      - conditions:
          - "{{ action == 'up_press' }}" # Second from highest button
          - condition: state
            entity_id: light.bedroom_lights
            state: "off"
        sequence:
          - action: light.turn_on
            entity_id: light.bedroom_lights

      # Turn off
      - conditions:
          - "{{ action == 'down_press' }}" # Second from lowest button
          - condition: state
            entity_id: light.bedroom_lights
            state: "on"
        sequence:
          - action: light.turn_off
            entity_id: light.bedroom_lights

      # Reset adaptive_lighting
      - conditions:
          - "{{ action == 'up_hold' }}" # Second from highest button
          - "{{ trigger.payload_json.action_duration > 2 }}" # Hold for more than two seconds
        sequence:
          - action: input_select.select_option
            entity_id: input_select.sleep_mode
            data:
              option: "off"
          - action: script.reset_adaptive_lighting

# This automation is set up to control the lighting in your bedroom using two different IKEA remotes.
# Here's a simplified explanation of the different actions that the automation performs:
# 1. **Bright Lights:** If you hold the top button on the remote and the bedroom lights are already on, the lights will become brighter, mimicking a bright daylight environment.
# 2. **Increase Brightness:** If you press the top button on the remote and the bedroom lights are already on, the brightness of the lights will increase.
# 3. **Turn On:** If you press the top button on the remote and the bedroom lights are off, the bedroom lights will turn on.
# 4. **Turn Off:** If you press the 'off' button on the remote and the bedroom lights are on, the bedroom lights will turn off.
# 5. **Next Color:** If you press the 'arrow left' button on the remote, the color of the bedroom lights will cycle to the next color in a predefined sequence.
# 6. **Turn on bedside light:** If you press the 'arrow right' button on the remote, a personal light (either the 'bamboo' light if using the first remote, or the 'philips go' light if using the second remote) will toggle on or off. If the personal light is already on, pressing the 'arrow right' button will increase the brightness of the personal light.
# 7. **Turn off everything (no guests):** If you hold the bottom button on the remote and there are no guests in the house (as determined by the status of 'guest mode'), all lights in the house will turn off.
# 8. **Turn off baby room and bedroom (with guests):** If you hold the bottom button on the remote and there are guests in the house, the lights in the bedroom, baby room, and the baby sphere light will turn off.
- alias: "Control switches: bedroom IKEA dimmer switch"
  mode: parallel
  triggers:
    - trigger: mqtt
      topic: "zigbee2mqtt/IKEA Remote (Bedroom)"
    - trigger: mqtt
      topic: "zigbee2mqtt/IKEA Remote (Bedroom Marcella)"
  variables:
    action: "{{ trigger.payload_json.action }}"
    personal_light: >-
      {% if trigger.topic == 'zigbee2mqtt/IKEA Remote (Bedroom)' %}
        light.bed_led
      {% elif trigger.topic == 'zigbee2mqtt/IKEA Remote (Bedroom Marcella)' %}
        light.philips_go
      {% endif %}
  actions:
    choose:
      # Bright lights
      - conditions:
          - "{{ action == 'brightness_move_up' }}" # Hold top button
          - condition: state
            entity_id: light.bedroom_lights
            state: "on"
        sequence:
          - action: script.white_lights_bedroom
          - action: light.turn_on
            entity_id: light.bedroom_lights
            data:
              brightness: "255"
              kelvin: 5500
          - action: input_select.select_option
            entity_id: input_select.sleep_mode
            data:
              option: "off"

      # Increase brightness
      - conditions:
          - "{{ action == 'on' }}" # Top button
          - condition: state
            entity_id: light.bedroom_lights
            state: "on"
        sequence:
          action: script.increase_brightness
          data:
            group: light.bedroom_lights

      # Turn on
      - conditions:
          - "{{ action == 'on' }}"
          - condition: state
            entity_id: light.bedroom_lights
            state: "off"
        sequence:
          - action: light.turn_on
            entity_id: light.bedroom_lights

      # Turn off
      - conditions:
          - "{{ action == 'off' }}"
          - condition: state
            entity_id: light.bedroom_lights
            state: "on"
        sequence:
          - action: light.turn_off
            entity_id: light.bedroom_lights

      # Next color
      - conditions: "{{ action == 'arrow_left_click' }}"
        sequence:
          action: script.next_colors
          data:
            input_select: input_select.last_script_bedroom

      # Turn on bedside light
      - conditions:
          - "{{ action == 'arrow_right_click' }}"
          - "{{ is_state(personal_light, 'off') }}"
        sequence:
          action: light.toggle
          data:
            entity_id: "{{ personal_light }}"
      - conditions:
          - "{{ action == 'arrow_right_click' }}"
          - "{{ is_state(personal_light, 'on') }}"
        sequence:
          action: script.increase_brightness
          data:
            group: "{{ personal_light }}"

      # Turn off everything (no guests)
      - conditions:
          - "{{ action == 'brightness_move_down' }}" # Hold lowest button
          - "{{ is_state('input_boolean.guest_mode', 'off') }}"
        sequence:
          - action: input_select.select_option
            data:
              entity_id: input_select.sleep_mode
              option: total
          - action: script.turn_off_everything

      # Turn off baby room and bedroom (with guests)
      - conditions:
          - "{{ action == 'brightness_move_down' }}" # Hold lowest button
          - "{{ is_state('input_boolean.guest_mode', 'on') }}"
        sequence:
          - action: input_select.select_option
            data:
              entity_id: input_select.sleep_mode
              option: total
          - action: light.turn_off
            data:
              entity_id:
                - light.bedroom_lights
                - light.bamboo
                - light.baby_room

- alias: "Control switches: living room Aqara Wireless Mini Switch"
  mode: parallel
  triggers:
    trigger: event
    event_type: deconz_event
    event_data:
      id: smart_switch_living_room
  actions:
    choose:
      # Next color
      - conditions: "{{ trigger.event.data.event == 1004 }}" # Double click
        sequence:
          action: script.next_colors
          data:
            input_select: input_select.last_script_living_room

      # Increase brightness
      - conditions: "{{ trigger.event.data.event == 1002 }}" # Single click
        sequence:
          action: script.increase_brightness
          data:
            group: light.living_room_lights

      # Turn off everything in the living room
      - conditions:
          - "{{ trigger.event.data.event == 1007 }}" # Shake button
          - condition: state
            entity_id: light.living_room_lights
            state: "on"
        sequence:
          - action: light.turn_on
            data:
              flash: "short"
              entity_id: light.cabinet_led
          - action: media_player.turn_off
            entity_id: media_player.tv
          - wait_template: "{{ is_state('media_player.tv', 'off') }}"
            timeout: "00:00:30"
          - action: media_player.turn_off
            entity_id: media_player.kef_ls50
          - action: light.turn_off
            entity_id: light.living_room_lights
            data:
              transition: 30

      # Fix the sounds on the TV (LG TV sound sync bug ðŸ›)
      - conditions: "{{ trigger.event.data.event == 1001 }}" # Long click
        sequence:
          action: script.fix_sound

- alias: "Control switches: bedroom Aqara Wireless Mini Switch"
  mode: parallel
  triggers:
    - trigger: event
      event_type: deconz_event
      event_data:
        id: smart_switch_bedroom_bas
    - trigger: event
      event_type: deconz_event
      event_data:
        id: smart_switch_bedroom_marcella
  actions:
    choose:
      # Next color
      - conditions: "{{ trigger.event.data.event == 1004 }}" # Double click
        sequence:
          action: script.next_colors
          data:
            input_select: input_select.last_script_bedroom

      # Increase brightness
      - conditions: "{{ trigger.event.data.event == 1002 }}" # Single click
        sequence:
          action: script.increase_brightness
          data:
            group: light.bedroom_lights

      # Turn off lights in and next to bedroom
      - conditions: "{{ trigger.event.data.event == 1001 }}" # Long click
        sequence:
          action: light.turn_off
          entity_id:
            - light.hall_lights
            - light.bedroom_lights
            - light.bathroom_ceiling
            - light.stairs_lights

      # Turn on sleep mode, else, turn all lights off
      - conditions: "{{ trigger.event.data.event == 1007 }}" # Shake button
        sequence:
          choose:
            - conditions: > # In the morning just turn lights off
                {% set h, m = states("sensor.ten_minutes_before_alarm").split(":") %}
                {% set t_diff = as_timestamp(now()) - as_timestamp(now().replace(hour=h|int(0), minute=m|int(0))) %}
                {% set is_near_alarm = (t_diff|abs) < 1800 %}
                {% set is_morning = now().replace(hour=6, minute=0) < now() < now().replace(hour=12, minute=0) %}
                {{ is_near_alarm or is_morning }}
              sequence:
                action: light.turn_off
                entity_id: all

            - conditions: # off -> half
                condition: state
                entity_id: input_select.sleep_mode
                state: "off"
              sequence:
                - action: light.turn_off
                  entity_id:
                    - light.hall_lights
                    - light.bedroom_lights
                    - light.bathroom_ceiling
                    - light.stairs_lights
                - action: input_select.select_option
                  entity_id: input_select.sleep_mode
                  data:
                    option: half

            - conditions: # half -> total
                condition: state
                entity_id: input_select.sleep_mode
                state: half
              sequence:
                - action: script.turn_off_everything
                - action: input_select.select_option
                  entity_id: input_select.sleep_mode
                  data:
                    option: total

            - conditions: # on total, just turn lights off
                condition: state
                entity_id: input_select.sleep_mode
                state: total
              sequence:
                action: light.turn_off
                entity_id: all

- alias: "Control switches: bathroom Aqara Wireless Mini Switch"
  mode: parallel
  triggers:
    trigger: event
    event_type: deconz_event
    event_data:
      id: smart_switch_bathroom
  actions:
    choose:
      # Toggle lights
      - conditions: "{{ trigger.event.data.event == 1002 }}" # Single click
        sequence:
          action: light.toggle
          entity_id: light.bathroom_lights

      # Flash all lights
      - conditions: "{{ trigger.event.data.event == 1004 }}" # Double click
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.living_room_lights
              flash: "short"

- alias: "Control switches: door Aqara Wireless Mini Switch"
  mode: parallel
  triggers:
    trigger: event
    event_type: deconz_event
    event_data:
      id: smart_switch_door
  actions:
    choose:
      # Leaving: turn off everything
      - conditions: "{{ trigger.event.data.event == 1002 }}" # Single click
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.living_room_lights
              flash: "short"
          - action: script.turn_off_everything_non_automatic
          - action: script.set_low_temperature
          - if: "{{ is_state_attr('media_player.spotify', 'source', 'KEF LS50') and is_state('media_player.spotify', 'playing') }}"
            then:
              - action: media_player.media_pause
                entity_id: media_player.spotify

      # Arriving: turn on music and cozy lights
      - conditions: "{{ trigger.event.data.event == 1004 }}" # Double click
        sequence:
          - action: light.turn_on
            data:
              flash: "short"
              entity_id: light.ceiling_kitchen
          - action: script.turn_on
            data:
              entity_id: light.living_room_lights
          - action: script.arriving
          - action: script.start_spotify
            data:
              source: KEF LS50
              id: 'playlist:{{ states("sensor.favorite_playlist_of_nearest_person") }}'
              volume: 0.25

- alias: "Control switches: guest room IKEA Switch"
  mode: parallel
  triggers:
    trigger: mqtt
    topic: "zigbee2mqtt/IKEA Switch (Guest room)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Turn on
      - conditions: "{{ action == 'on' }}" # Lowest button
        sequence:
          action: light.turn_on
          entity_id: light.guest_room_lights

      # Turn off
      - conditions: "{{ action == 'off' }}" # Lowest button
        sequence:
          action: light.turn_off
          entity_id: light.guest_room_lights

- alias: "Control switches: Guest Room Light"
  mode: parallel
  triggers:
    - trigger: mqtt
      topic: "zigbee2mqtt/Smart Switch (Guest Room)"
    - trigger: mqtt
      topic: "zigbee2mqtt/Smart Switch (Desk)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Toggle
      - conditions: "{{ action == 'single' }}"
        sequence:
          action: light.toggle
          data:
            entity_id: light.guest_room_lights

      # Toggle sleep mode
      - conditions: "{{ action == 'double' }}"
        sequence:
          action: switch.toggle
          entity_id: switch.adaptive_lighting_sleep_mode_guest_room

- alias: "Control switches: Guest Room Space heater"
  mode: parallel
  triggers:
    trigger: mqtt
    topic: "zigbee2mqtt/Smart Switch (Desk)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Toggle
      - conditions: "{{ action == 'single' }}"
        sequence:
          action: switch.toggle
          data:
            entity_id: switch.space_heater

- alias: "Control switches: Baby Room Light"
  mode: parallel
  triggers:
    trigger: mqtt
    topic: "zigbee2mqtt/Smart Switch (Baby Room)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Toggle light
      - conditions: "{{ action == 'single' }}"
        sequence:
          action: light.toggle
          data:
            entity_id:
              - light.bamboo
              - light.baby_room

      # Toggle sleep mode
      - conditions: "{{ action == 'double' }}"
        sequence:
          action: switch.toggle
          entity_id: switch.adaptive_lighting_sleep_mode_baby_room

- alias: "Control switches: Mid Room Changing Table Light"
  mode: parallel
  triggers:
    trigger: mqtt
    topic: "zigbee2mqtt/Smart Switch (Mid Room)"
  variables:
    action: "{{ trigger.payload_json.action }}"
  actions:
    choose:
      # Toggle
      - conditions: "{{ action == 'single' }}"
        sequence:
          action: light.toggle
          data:
            entity_id: light.mid_room
            brightness_pct: 100
            color_temp_kelvin: 2200

      # Change brightness
      - conditions: "{{ action == 'double' }}"
        sequence:
          action: script.increase_brightness
          data:
            group: light.mid_room

      # Next colors
      - conditions: "{{ action == 'hold' }}"
        sequence:
          action: script.next_colors
          data:
            input_select: input_select.last_script_living_room
