---
#-
#                  _ _ _
#  _ __ ___   __ _(_) | |__   _____  __
# | '_ ` _ \ / _` | | | '_ \ / _ \ \/ /
# | | | | | | (_| | | | |_) | (_) >  <
# |_| |_| |_|\__,_|_|_|_.__/ \___/_/\_\
#
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Mailbox: the mailbox was opened"
  description: |
    In the UI show the `input_boolean.mailbox_full`. It needs to
    be manually switched off after getting the mail."
  triggers:
    - platform: state
      entity_id: binary_sensor.mailbox_vibration
      to: "on"
  conditions:
    - condition: state
      entity_id: input_boolean.mailbox_full
      state: "off"
  action:
    - service: notify.all_iphones
      data:
        title: "Mailbox"
        message: "Received mail in the mailbox!"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.mailbox_full
