---
#-
#                       _   _                                     _
# __   ____ _  ___ __ _| |_(_) ___  _ __      _ __ ___   ___   __| | ___
# \ \ / / _` |/ __/ _` | __| |/ _ \| '_ \    | '_ ` _ \ / _ \ / _` |/ _ \
#  \ V / (_| | (_| (_| | |_| | (_) | | | |   | | | | | | (_) | (_| |  __/
#   \_/ \__,_|\___\__,_|\__|_|\___/|_| |_|___|_| |_| |_|\___/ \__,_|\___|
#                                       |_____|
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Vacation mode: auto turn on"
  initial_state: "on"
  triggers:
    trigger: state
    entity_id: group.persons
    from: home
    to: not_home
    for: "24:00:00"
  conditions:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  actions:
    - action: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - action: notify.all_iphones
      data:
        title: "Vacation mode"
        message: "No one at home for 24 hours, switching on vacation mode."

- alias: "Vacation mode: auto turn off"
  initial_state: "on"
  triggers:
    trigger: state
    entity_id: group.persons
    from: not_home
    to: home
  conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "on"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  actions:
    - action: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
    - action: notify.all_iphones
      data:
        title: "Vacation mode"
        message: "Welcome back! Switching off the vacation mode."

- alias: "Vacation mode: lower high temperature"
  triggers:
    trigger: state
    entity_id: input_boolean.vacation_mode
    to: "on"
  actions:
    - action: input_number.set_value
      entity_id: input_number.temperature_high
      data:
        value: 15

- alias: "Vacation mode: restore high temperature"
  triggers:
    trigger: state
    entity_id: input_boolean.vacation_mode
    to: "off"
  actions:
    - action: input_number.set_value
      entity_id: input_number.temperature_high
      data:
        value: 20.5
