---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/basnijholt/home-assistant-config
- platform: group
  name: Living room lights
  entities:
    - light.sphere_tv
    - light.sphere_2
    - light.living_room_corner
    - light.tv_led
    - light.cabinet_led
    - light.mid_room
    - light.shelve
    - light.marble

- platform: group
  name: Bedroom lights
  entities:
    - light.philips_go
    - light.bed_led
    - light.bamboo

- platform: group
  name: Automatic lights
  entities:
    - light.utility_room
    - light.garage_outside
    - light.guest_room
    - light.baby_room
    - light.baby_sphere
    - light.outside_front_door
    - light.bedroom_outside

- platform: group
  name: Kitchen lights
  entities:
    - light.dinner_area

- platform: switch
  name: Baby sphere
  entity_id: switch.baby_sphere

- platform: switch
  name: Guest room
  entity_id: switch.guest_room

# - platform: group
#   name: Bathroom lights
#   entities:
#     - light.bathroom_ceiling
#     - light.bathroom_mirror

# - platform: group
#   name: Bed reading
#   entities:
#     - light.bed_reading_up
#     - light.bed_reading_down
