---
#-
#
#  ___  ___ _ __  ___  ___  _ __ ___
# / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# \__ \  __/ | | \__ \ (_) | |  \__ \
# |___/\___|_| |_|___/\___/|_|  |___/
#
#
#- from github.com/basnijholt/home-assistant-config

#   ___  _   _
#  / _ \| |_| |__   ___ _ __ ___
# | | | | __| '_ \ / _ \ '__/ __|
# | |_| | |_| | | |  __/ |  \__ \
#  \___/ \__|_| |_|\___|_|  |___/
#

- platform: statistics
  name: Humidity bathroom stats
  entity_id: sensor.humidity_bathroom
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age: "24:00:00"
  state_characteristic: mean

- platform: derivative
  source: sensor.humidity_bathroom
  name: Humidity bathroom derivative
  unit_time: min
  time_window: "00:10:00"

# XXX: not used
- platform: min_max
  name: Temperature mean
  type: mean
  entity_ids:
    - sensor.temperature_living_room
    - sensor.temperature_bedroom
    - sensor.temperature_bathroom
    - sensor.temperature_hall

- platform: time_date
  display_options:
    - date
    - time

#  _____ _                  _                  _
# |_   _(_)_ __ ___   ___  | |_ _ __ __ _  ___| | _____ _ __ ___
#   | | | | '_ ` _ \ / _ \ | __| '__/ _` |/ __| |/ / _ \ '__/ __|
#   | | | | | | | | |  __/ | |_| | | (_| | (__|   <  __/ |  \__ \
#   |_| |_|_| |_| |_|\___|  \__|_|  \__,_|\___|_|\_\___|_|  |___/
#

- platform: history_stats
  name: Hours TV has been on last 7 days
  entity_id: media_player.tv
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times TV has been on last 7 days
  entity_id: media_player.tv
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dishwasher has been on last 7 days
  entity_id: binary_sensor.dishwasher
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times dishwasher has been on last 7 days
  entity_id: binary_sensor.dishwasher
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours washing machine has been on last 7 days
  entity_id: binary_sensor.washing_machine
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times washing machine has been on last 7 days
  entity_id: binary_sensor.washing_machine
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Bas
  entity_id: person.bas
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Marcella
  entity_id: person.marcella
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Bas times left
  entity_id: person.bas
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Marcella times left
  entity_id: person.marcella
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bedroom lights have been on last 7 days
  entity_id: light.bedroom_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours living room lights have been on last 7 days
  entity_id: light.living_room_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours toilet light has been on last 7 days
  entity_id: light.toilet
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours kitchen lights have been on last 7 days
  entity_id: light.kitchen_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours hall lights have been on last 7 days
  entity_id: light.hall_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bathroom light has been on last 7 days
  entity_id: light.bathroom_ceiling
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

  # __        __         _      _   _                  _                  _
# \ \      / /__  _ __| | __ | |_(_)_ __ ___   ___  | |_ _ __ __ _  ___| | _____ _ __
#  \ \ /\ / / _ \| '__| |/ / | __| | '_ ` _ \ / _ \ | __| '__/ _` |/ __| |/ / _ \ '__|
#   \ V  V / (_) | |  |   <  | |_| | | | | | |  __/ | |_| | | (_| | (__|   <  __/ |
#    \_/\_/ \___/|_|  |_|\_\  \__|_|_| |_| |_|\___|  \__|_|  \__,_|\___|_|\_\___|_|
#

- platform: history_stats
  name: Time at work this week
  entity_id: person.bas
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float(0) - now().weekday() * 86400 }}
  end: "{{ now() }}"

- platform: history_stats
  name: Time at work today
  entity_id: person.bas
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float(0) - 0 * 86400 }}
  duration:
    hours: 24

- platform: history_stats
  name: Time at work on Monday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 0 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Tuesday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 1 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Wednessday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 2 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Thursday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 3 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Friday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 4 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

#  ____                                          _    ____
# |  _ \ _____      _____ _ __    __ _ _ __   __| |  / ___| __ _ ___
# | |_) / _ \ \ /\ / / _ \ '__|  / _` | '_ \ / _` | | |  _ / _` / __|
# |  __/ (_) \ V  V /  __/ |    | (_| | | | | (_| | | |_| | (_| \__ \
# |_|   \___/ \_/\_/ \___|_|     \__,_|_| |_|\__,_|  \____|\__,_|___/

# From the "Meterkast" Home Assistant

# - platform: mqtt
#   state_topic: homeassistant/sensor/gas_consumption/state
#   unit_of_measurement: m続
#   name: Gas Consumption
#   icon: mdi:fire
#   device_class: gas
#   state_class: total_increasing

# - platform: mqtt
#   state_topic: homeassistant/sensor/hourly_gas_consumption/state
#   unit_of_measurement: m続/h
#   name: Hourly Gas Consumption
#   icon: mdi:fire
#   device_class: gas
#   state_class: total_increasing

# - platform: mqtt
#   state_topic: homeassistant/sensor/power_consumption/state
#   unit_of_measurement: kW
#   name: Power Consumption
#   icon: mdi:flash
#   device_class: power
#   state_class: measurement

# - platform: mqtt
#   state_topic: homeassistant/sensor/energy_consumption_tarif_1/state
#   unit_of_measurement: kWh
#   name: Energy Consumption (tarif 1)
#   icon: mdi:flash
#   device_class: energy
#   state_class: total_increasing

# - platform: mqtt
#   state_topic: homeassistant/sensor/energy_consumption_tarif_2/state
#   unit_of_measurement: kWh
#   name: Energy Consumption (tarif 2)
#   icon: mdi:flash
#   device_class: energy
#   state_class: total_increasing

# - platform: mqtt
#   state_topic: homeassistant/sensor/power_tariff/state
#   name: Power Tariff
#   icon: mdi:flash

- platform: filter
  name: "Gas consumption filtered"
  entity_id: sensor.gas_consumption
  filters:
    - filter: time_simple_moving_average
      window_size: 00:30:00
      precision: 2

- platform: derivative
  source: sensor.gas_consumption
  name: Gas per hour
  unit: m続/h
  unit_time: h
  time_window: "00:30:00"

- platform: derivative
  source: sensor.gas_consumption_filtered
  name: Gas per hour (filtered)
  unit: m続/h
  unit_time: h
