---
#-
#               _ _       _
#  _____      _(_) |_ ___| |__   ___  ___
# / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# \__ \\ V  V /| | || (__| | | |  __/\__ \
# |___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#
#
#- from github.com/basnijholt/home-assistant-config
- platform: template
  switches:
    vacuum_mode:
      value_template: >
        {{ is_state("vacuum.xiaomi_vacuum_cleaner", "cleaning")}}
      turn_on:
        service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner

    kef_lsx:
      friendly_name: Bedroom speakers
      value_template: >
        {{ is_state("media_player.kef_lsx", "on") }}
      availability_template: >
        {{ not is_state("media_player.kef_lsx", "unavailable") }}
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.kef_lsx
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.kef_lsx

- platform: circadian_lighting
  lights_rgb:
    - light.philips_go
    - light.bamboo
    - light.ceiling_bedroom
    - light.lampan
    - light.bed_led
    - light.bed_reading_up
    - light.bed_reading_down
    - light.ceiling_bathroom
    - light.toilet
    - light.ceiling_kitchen
  lights_ct:
    - light.stairs_up
    - light.stairs_down
    - light.hall_1
    - light.hall_2
    - light.hall_3
  sleep_state: total
  disable_state: half
  profile: default

- platform: circadian_lighting
  name: "half and dim"
  lights_rgb:
    - light.philips_go
    - light.bamboo
    - light.ceiling_bedroom
    - light.lampan
    - light.bed_led
    - light.bed_reading_up
    - light.bed_reading_down
    - light.ceiling_bathroom
  lights_ct:
    - light.hall_2
    - light.hall_3
  sleep_state: half
  disable_state:
    - total
    - "off"
  profile: default

- platform: circadian_lighting
  name: "half and full"
  lights_rgb:
    - light.toilet
    - light.ceiling_kitchen
  lights_ct:
    - light.stairs_up
    - light.stairs_down
    - light.hall_1
  disable_state:
    - total
    - "off"
  profile: default
