---
#-
#               _ _       _
#  _____      _(_) |_ ___| |__   ___  ___
# / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# \__ \\ V  V /| | || (__| | | |  __/\__ \
# |___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#
#
#- from github.com/basnijholt/home-assistant-config
- platform: template
  switches:
    vacuum_mode:
      value_template: >
        {{ is_state("vacuum.robot_vacuum", "cleaning")}}
      turn_on:
        service: vacuum.start
        entity_id: vacuum.robot_vacuum
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.robot_vacuum
